### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by d1mnewz** [orbit-love/community-js-reddit-orbit#4]
Hey, thanks for putting that integration in place! 

I was not able to use it, even though followed the guide. Is there any way for us to figure out what is the problem?

Only thing I get as response to my command:
> npx @orbit-love/reddit --posts --comments --subreddit=portainer --hours=24

is 
> Unhandled rejection StatusCodeError: 401 - {"message":"Unauthorized","error":401}

with the following stack trace
```
Unhandled rejection StatusCodeError: 401 - {"message":"Unauthorized","error":401}
    at new StatusCodeError (/home/dimko/.npm/_npx/3806/lib/node_modules/@orbit-love/reddit/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/home/dimko/.npm/_npx/3806/lib/node_modules/@orbit-love/reddit/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/home/dimko/.npm/_npx/3806/lib/node_modules/@orbit-love/reddit/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/home/dimko/.npm/_npx/3806/lib/node_modules/@orbit-love/reddit/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/home/dimko/.npm/_npx/3806/lib/node_modules/@orbit-love/reddit/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/home/dimko/.npm/_npx/3806/lib/node_modules/@orbit-love/reddit/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1224:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

I am sure that reddit credentials that I put are correct, also I am sure that this user is the developer on reddit app. I'm using env variables to set the credentials. Tried to debug it, but not so much to debug against reddit API response code... 

Am I missing anythig?

**Comment by mxdavis** [comment]
Hi @d1mnewz, 

[> *PLEASE NOTE: For this to work, your Reddit account should have 2FA disabled AND needs to have a password set.

>If you used your Google or Apple account to sign up to Reddit and don't have an account, you could disconnect it, and then you'll be able to set an account (and reconnect your Google or Apple account after).
>If you want 2FA enabled on your main Reddit account (you probably should): create an additional account to set up this integration and don't use your main account.](https://github.com/orbit-love/community-js-reddit-orbit#username-cannot-have-2fa)

Does your username have 2FA enabled?

Let me know if that's the issue.

**Comment by d1mnewz** [comment]
> Hi @d1mnewz,
> 
> [> *PLEASE NOTE: For this to work, your Reddit account should have 2FA disabled AND needs to have a password set.
> 
> > If you used your Google or Apple account to sign up to Reddit and don't have an account, you could disconnect it, and then you'll be able to set an account (and reconnect your Google or Apple account after).
> > If you want 2FA enabled on your main Reddit account (you probably should): create an additional account to set up this integration and don't use your main account.]([orbit-love/community-js-reddit-orbit#username-cannot-have-2fa](https://github.com/orbit-love/community-js-reddit-orbit#username-cannot-have-2fa))
> 
> Does your username have 2FA enabled?
> 
> Let me know if that's the issue.

Nope, no 2FA, has the password. I also created a fresh account from other email and with its credentials I have the same problem.

**Comment by mxdavis** [comment]
> Nope, no 2FA, has the password. I also created a fresh account from other email and with its credentials I have the same problem.

See if this works:

`Run npx @orbit-love/reddit --posts --comments --hours=24 --subreddit "portainer"`

Have you double-checked all the creds, even the orbit ones?

**Comment by d1mnewz** [comment]
> > Nope, no 2FA, has the password. I also created a fresh account from other email and with its credentials I have the same problem.
> 
> See if this works:
> 
> `Run npx @orbit-love/reddit --posts --comments --hours=24 --subreddit "portainer"`
> 
> Have you double-checked all the creds, even the orbit ones?

Hey, running this command helped. 
Unfortunately, only 24 hours command worked out, If I try with 100 hours, it fails with the following stack trace.

```
dimko@DESKTOP-KVKFCQP-wsl:/mnt/c/users/owner/source/repos/dev-tools/kubernetes/kind$ npx @orbit-love/reddit --posts --comments --hours=100 --subreddit "portainer"
npx: installed 80 in 3.178s
Fetched 5 posts from the provided timeframe
Posts are prepared as Orbit activities. Sending them off now...
(node:103866) UnhandledPromiseRejectionWarning: ReferenceError: errors is not defined
    at /home/dimko/.npm/_npx/103866/lib/node_modules/@orbit-love/reddit/src/index.js:67:36
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /home/dimko/.npm/_npx/103866/lib/node_modules/@orbit-love/reddit/src/index.js:63:21
(Use `node --trace-warnings ...` to show where the warning was created)
(node:103866) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:103866) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mxdavis** [comment]
@d1mnewz Hope you had enjoyed the holidays! I'm working on a fix here. I'm pretty sure it's erroring out because of incorrect handling of duplicate activities. I will deploy a fix and update you soon.

**Comment by mxdavis** [comment]
@d1mnewz give it a try again. For now, I focused on better error handling so it will not break, and hopefully print some errors. Let me know what you find.

**Comment by d1mnewz** [comment]
Great! The fix seemed to work. Now I do have the automation in Github Actions, and everything works as a charm. Feel free to close the issue, everything is solved! 

Great job @mxdavis, appreciate it!
